### ISSUE TITLE
[http] Add a context manager  for response object

### ISSUE THREAD

**Issue by noxiouz** [cocaine/cocaine-framework-python#29]
``` python
@http 
def f(request, response):
    with response:
        pass
```

raises **exit**

**Comment by 3Hren** [comment]
Why?

**Comment by noxiouz** [comment]
Because it's a python way to use context manager to close response. ```@http``` changes a type of the argument from response (it has __exit__) to HTTPResponse, which hasn't.

**Comment by 3Hren** [comment]
Ok, what would be if the response won't be closed explicitly by user (raised exception or just forgot to)? I thought you close it for him.

**Comment by noxiouz** [comment]
Yes, it would be closed, but it sends a plain error message.  In case of http we could send proper status code, headers and well formatted body if it's possible

**Comment by 3Hren** [comment]
How do you select proper status code / headers / body for user? Is it configurable when context manager enters or somewhere else?

**Comment by noxiouz** [comment]
For example:
```python
wih response(*args, **kwargs):
```

**Comment by 3Hren** [comment]
Timeout.
