### ISSUE TITLE
Current example of usage cocaine app

### ISSUE THREAD

**Issue by Alukardd** [cocaine/cocaine-framework-python#38]
Hello.

Can you show me actual example of usage cocaine apps on different languages, at least python.
Example in [wiki](https://github.com/cocaine/cocaine-framework-python/wiki/Echo-application-example) is too old and doesn't work.
```
AttributeError: 'Future' object has no attribute 'get'
```

As app, I use example —  cocaine-framework-python/examples/echo/\__init__.py

**Comment by noxiouz** [comment]
Updated
